development:
  secret_key_base: 2c50030512d8a20c9c13893a1cb6a957b5d0cd2678af90a62ba69e1f68603d9f8a2631102baf0017f5ed5b4b97d757c7d5a68bcaec77eea00b3ccb6047073115
  facebook:
    key: 1590678351168245
    secret: 110f679f2b5bb959ec5f153af68e7428
  google_oauth2:
    key: 917225356539-u0162u4pan03dmu58krtantejo86ljij.apps.googleusercontent.com
    secret: BmYss8oeeUqho4RRobDwMC7e

  braintree:
    merchant_id: MERCHANT_ID
    public_key: PUBLIC_KEY
    private_key: PRIVATE_KEY
    master_merchant_id: MASTER_MERCHANT_ID

  s3:
    aws_access_key_id: AKIAIZCB2JTA6CET7UNQ
    aws_secret_access_key: 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
    region: ca-central-1
    provider: AWS
    s3_url_prefix: //s3.ca-central-1.amazonaws.com
    s3_bucket: homestohotels
    s3_protocol: 'https:'
    assets_path: assets
  twilio:
    account_sid: AC1bdd41a3b379b3cd3e1c25eefc590306
    auth_token: 225271acb34d59801c501d99ee351b27
    phone: 16475593395
  root_path: https://homes2hotels.ca

production:
  secret_key_base: 2c50030512d8a45c9c13899r1cb6a957b5d0cd2678af90a62ba69e1f68603d9f8a2631102baf0017f5ed5b4b97d757c7d5a68bcaec77eea00b3ccb6047073115
  facebook:
    key: 395174171018904
    secret: b351b70d718becbc1d70d890158ca0ea
  google_oauth2:
    key: 917225356539-u0162u4pan03dmu58krtantejo86ljij.apps.googleusercontent.com
    secret: BmYss8oeeUqho4RRobDwMC7e
  braintree:
    merchant_id: hc68gmk464v3pcxk
    public_key: n5k7vhkc9mkw94fg
    private_key: f52935ead0038ea6e7c07605981d8bcc
    master_merchant_id: yuvasoft
  s3:
    aws_access_key_id: AKIAIZCB2JTA6CET7UNQ
    aws_secret_access_key: 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
    region: ca-central-1
    provider: AWS
  twilio:
    account_sid: AC1bdd41a3b379b3cd3e1c25eefc590306
    auth_token: 225271acb34d59801c501d99ee351b27
    phone: 16475593395
  root_path: https://homes2hotels.ca
